#!/usr/bin/env python3
"""
generate_routes.py
Panther Cloud Air — Route and Aircraft SQL Generator
CSC 4710 Spring 2026

Computes:
  1. Great-circle distance (miles + km) between all 31 airport pairs
  2. Initial bearing (heading in degrees) for each route
  3. Filters out routes < 150 miles
  4. Outputs SQL INSERT statements for routes + aircraft tables
"""

import math
import itertools

# ---------------------------------------------------------------------------
# Airport data  (matches init.sql exactly)
# ---------------------------------------------------------------------------
AIRPORTS = [
    ("ATL",  33.6407, -84.4277,  True),
    ("LAX",  33.9425,-118.4081,  True),
    ("ORD",  41.9742, -87.9073,  True),
    ("DFW",  32.8998, -97.0403,  True),
    ("DEN",  39.8561,-104.6737, False),
    ("JFK",  40.6413, -73.7781, False),
    ("SFO",  37.6213,-122.3790, False),
    ("SEA",  47.4502,-122.3088, False),
    ("LAS",  36.0840,-115.1537, False),
    ("MCO",  28.4294, -81.3090, False),
    ("MIA",  25.7959, -80.2870, False),
    ("CLT",  35.2140, -80.9431, False),
    ("PHX",  33.4373,-112.0078, False),
    ("IAH",  29.9902, -95.3368, False),
    ("BOS",  42.3656, -71.0096, False),
    ("MSP",  44.8848, -93.2223, False),
    ("FLL",  26.0726, -80.1527, False),
    ("DTW",  42.2162, -83.3554, False),
    ("PHL",  39.8719, -75.2411, False),
    ("LGA",  40.7769, -73.8740, False),
    ("MDW",  41.7868, -87.7522, False),
    ("BWI",  39.1754, -76.6683, False),
    ("SLC",  40.7884,-111.9778, False),
    ("DCA",  38.8512, -77.0402, False),
    ("SAN",  32.7338,-117.1933, False),
    ("MCI",  39.2976, -94.7139, False),
    ("STL",  38.7487, -90.3700, False),
    ("HNL",  21.3187,-157.9224, False),
    ("PDX",  45.5898,-122.5951, False),
    ("BNA",  36.1263, -86.6774, False),
    ("CDG",  49.0097,   2.5479, False),
]

R_KM   = 6371.0
R_MI   = 3958.8
KM2MI  = 0.621371
MIN_DIST_MI = 150.0

def haversine_km(lat1, lon1, lat2, lon2):
    """Return great-circle distance in km."""
    la1, lo1, la2, lo2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlat = la2 - la1
    dlon = lo2 - lo1
    a = math.sin(dlat/2)**2 + math.cos(la1)*math.cos(la2)*math.sin(dlon/2)**2
    return 2 * R_KM * math.asin(math.sqrt(a))

def initial_bearing(lat1, lon1, lat2, lon2):
    """Return initial bearing (0=N, 90=E, 180=S, 270=W) in degrees."""
    la1, lo1, la2, lo2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlon = lo2 - lo1
    x = math.sin(dlon) * math.cos(la2)
    y = math.cos(la1)*math.sin(la2) - math.sin(la1)*math.cos(la2)*math.cos(dlon)
    bearing = math.degrees(math.atan2(x, y))
    return (bearing + 360) % 360

# ---------------------------------------------------------------------------
# Generate routes
# ---------------------------------------------------------------------------
routes = []
excluded = []

for (iata1, lat1, lon1, hub1), (iata2, lat2, lon2, hub2) in itertools.combinations(AIRPORTS, 2):
    km   = haversine_km(lat1, lon1, lat2, lon2)
    mi   = km * KM2MI
    hdg  = initial_bearing(lat1, lon1, lat2, lon2)
    intl = (iata1 == "CDG" or iata2 == "CDG")

    if mi < MIN_DIST_MI:
        excluded.append((iata1, iata2, round(mi, 1)))
    else:
        routes.append({
            "origin":  iata1,
            "dest":    iata2,
            "dist_mi": round(mi, 2),
            "dist_km": round(km, 2),
            "heading": round(hdg, 2),
            "intl":    intl,
        })
        # Also add reverse direction
        rev_hdg = initial_bearing(lat2, lon2, lat1, lon1)
        routes.append({
            "origin":  iata2,
            "dest":    iata1,
            "dist_mi": round(mi, 2),
            "dist_km": round(km, 2),
            "heading": round(rev_hdg, 2),
            "intl":    intl,
        })

# ---------------------------------------------------------------------------
# Print summary
# ---------------------------------------------------------------------------
print("-- ============================================================")
print("-- PCA Route Data (auto-generated by generate_routes.py)")
print("-- ============================================================")
print()
print("-- Routes EXCLUDED (< 150 miles):")
for o, d, m in sorted(excluded, key=lambda x: x[2]):
    print(f"--   {o} <-> {d}  ({m} mi)")
print()
print(f"-- Total valid directional routes: {len(routes)}")
print(f"-- Total valid unique pairs: {len(routes)//2}")
print()
print("-- ------------------------------------------------------------")
print("-- INSERT routes")
print("-- ------------------------------------------------------------")
print("INSERT INTO routes (origin_iata, dest_iata, distance_miles, distance_km, heading_degrees, is_international) VALUES")
rows = []
for r in sorted(routes, key=lambda x: (x["origin"], x["dest"])):
    intl_val = "TRUE" if r["intl"] else "FALSE"
    rows.append(
        f"  ('{r['origin']}','{r['dest']}',{r['dist_mi']},{r['dist_km']},{r['heading']},{intl_val})"
    )
print(",\n".join(rows) + ";")
print()

# ---------------------------------------------------------------------------
# Aircraft fleet
# ---------------------------------------------------------------------------
print()
print("-- ------------------------------------------------------------")
print("-- INSERT aircraft fleet")
print("-- 15x Boeing 737-600  (type_id=1)  tail: N601CA–N615CA")
print("-- 15x Boeing 737-800  (type_id=2)  tail: N801CA–N815CA")
print("-- 12x Airbus A200-100 (type_id=3)  tail: N221CA–N232CA")
print("-- 13x Airbus A220-300 (type_id=4)  tail: N231CA–N243CA")
print("-- Start positions spread across hubs; remaining at other airports")
print("-- ------------------------------------------------------------")

# Distribute starting airports — spread across all airports, hubs preferred
starting_airports = {
    # 737-600 (15): spread across all hubs + a few non-hubs
    "N601CA": "ATL", "N602CA": "ATL", "N603CA": "ATL", "N604CA": "ATL",
    "N605CA": "ORD", "N606CA": "ORD", "N607CA": "ORD", "N608CA": "ORD",
    "N609CA": "DFW", "N610CA": "DFW", "N611CA": "DFW", "N612CA": "DFW",
    "N613CA": "LAX", "N614CA": "LAX", "N615CA": "LAX",
    # 737-800 (15): spread
    "N801CA": "ATL", "N802CA": "ATL", "N803CA": "ATL",
    "N804CA": "ORD", "N805CA": "ORD", "N806CA": "ORD",
    "N807CA": "DFW", "N808CA": "DFW", "N809CA": "DFW",
    "N810CA": "LAX", "N811CA": "LAX", "N812CA": "LAX",
    "N813CA": "JFK", "N814CA": "BOS", "N815CA": "MIA",
    # A200-100 (12): regional markets
    "N221CA": "ATL", "N222CA": "ORD", "N223CA": "DFW", "N224CA": "LAX",
    "N225CA": "JFK", "N226CA": "SFO", "N227CA": "SEA", "N228CA": "PHX",
    "N229CA": "DEN", "N230CA": "MSP", "N231CA": "DTW", "N232CA": "CLT",
    # A220-300 (13): international + long-haul; one reserved for JFK-CDG
    "N301CA": "JFK",   # JFK-CDG service
    "N302CA": "ATL", "N303CA": "ORD", "N304CA": "DFW", "N305CA": "LAX",
    "N306CA": "BOS", "N307CA": "MIA", "N308CA": "IAH", "N309CA": "SEA",
    "N310CA": "SFO", "N311CA": "DEN", "N312CA": "PHX", "N313CA": "MSP",
}

# Build aircraft type map
type_map = {}
for tail in starting_airports:
    prefix = tail[1:4]
    if prefix == "601" or prefix.startswith("6") and int(prefix) <= 615:
        type_map[tail] = 1  # 737-600
    elif prefix.startswith("8") and int(prefix) <= 815:
        type_map[tail] = 2  # 737-800
    elif prefix.startswith("2"):
        type_map[tail] = 3  # A200-100
    elif prefix.startswith("3"):
        type_map[tail] = 4  # A220-300

# Re-do cleaner type assignment
aircraft_list = []
for i in range(1, 16):
    aircraft_list.append((f"N{600+i}CA", 1, list(starting_airports.values())[i-1]))
for i in range(1, 16):
    aircraft_list.append((f"N{800+i}CA", 2, list(starting_airports.values())[15+i-1]))
for i in range(1, 13):
    aircraft_list.append((f"N{220+i}CA", 3, list(starting_airports.values())[30+i-1]))
for i in range(1, 14):
    aircraft_list.append((f"N{300+i}CA", 4, list(starting_airports.values())[42+i-1]))

# Use the starting_airports dict directly
print("INSERT INTO aircraft (tail_number, type_id, current_airport, status, flight_hours) VALUES")
rows = []
for tail, airport in starting_airports.items():
    # Determine type_id from tail number
    num = int(tail[1:4])
    if 601 <= num <= 615:
        t = 1
    elif 801 <= num <= 815:
        t = 2
    elif 221 <= num <= 232:
        t = 3
    else:
        t = 4
    rows.append(f"  ('{tail}',{t},'{airport}','active',0.00)")
print(",\n".join(rows) + ";")

# ---------------------------------------------------------------------------
# Print distance matrix summary (top airport pairs)
# ---------------------------------------------------------------------------
print()
print("-- ============================================================")
print("-- DISTANCE REFERENCE TABLE (unique pairs, sorted by distance)")
print("-- ============================================================")
unique = [r for r in routes if r["origin"] < r["dest"]]
unique.sort(key=lambda x: x["dist_mi"])
print("-- CLOSEST valid pairs (150–300 miles):")
for r in [x for x in unique if x["dist_mi"] < 300]:
    print(f"--   {r['origin']} <-> {r['dest']}: {r['dist_mi']} mi / {r['dist_km']} km  hdg:{r['heading']}°")

print()
print("-- LONGEST pairs (>2000 miles):")
for r in sorted(unique, key=lambda x: -x["dist_mi"])[:15]:
    print(f"--   {r['origin']} <-> {r['dest']}: {r['dist_mi']} mi / {r['dist_km']} km")
